### ISSUE TITLE
Startup mode nvidia_once doesn't work

### ISSUE THREAD

**Issue by JpegXguy** [Askannz/optimus-manager#112]
**Describe the bug**
If startup mode is `nvidia_once` the boot setup script will fail with the following error and write **no** configuration in `/etc/X11/xorg.conf.d`. In my case X autoselects intel.

**System info**
Arch Linux, Cinnamon, LightDM
optimus-manager 1.1-1

**Logs**
`/var/log/optimus-manager/boot_setup.log`

```
Optimus Manager (Setup script) version 1.1
Setting up boot
Cleaning up leftover Xorg conf
Loading config
Reading startup mode
No kernel parameter set for startup, reading from file
Startup mode is : nvidia_once
Writing startup mode to requested GPU mode
Writing requested mode
Traceback (most recent call last):
  File "/usr/bin/optimus-manager-setup", line 11, in <module>
    load_entry_point('optimus-manager==1.1', 'console_scripts', 'optimus-manager-setup')()
  File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_setup.py", line 49, in main
    _write_gpu_mode(config, startup_mode)
  File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_setup.py", line 125, in _write_gpu_mode
    var.write_requested_mode(mode)
  File "/usr/lib/python3.7/site-packages/optimus_manager/var.py", line 33, in write_requested_mode
    assert mode in ["intel", "nvidia"]
AssertionError
```

**Comment by Askannz** [comment]
Yeah, `nvidia_once` has been deprecated. I forgot to update the README, sorry.

**Comment by JpegXguy** [comment]
I saw no indication of that, because the mode is considered valid. If this is fixed I think we're done :)
```
$ optimus-manager --set-startup wg

Invalid startup mode : wg
$ optimus-manager --set-startup nvidia_once

setting startup mode to : nvidia_once
```

**Comment by Askannz** [comment]
Whoopsie.
