### ISSUE TITLE
optimus-manager-daemon couldn't start 

### ISSUE THREAD

**Issue by seewpx** [Askannz/optimus-manager#148]
**Describe the bug**
It seems to be some problems with python3.6. It throws out TypeError: cannot deepcopy this pattern object.
```shell
xu@xu-matebook ~ $ /usr/bin/python3 -u /usr/bin/optimus-manager-daemon
Optimus Manager (Daemon) version 1.2.1
Automatic log cropping
Loading config file
Traceback (most recent call last):
  File "/usr/bin/optimus-manager-daemon", line 86, in <module>
    exec(data, new_globals)
  File "<string>", line 11, in <module>
  File "/usr/lib64/python3.6/site-packages/optimus_manager/optimus_manager_daemon.py", line 24, in main
    config = _get_config()
  File "/usr/lib64/python3.6/site-packages/optimus_manager/optimus_manager_daemon.py", line 44, in _get_config
    config = load_config()
  File "/usr/lib64/python3.6/site-packages/optimus_manager/config.py", line 16, in load_config
    validate_config(base_config)
  File "/usr/lib64/python3.6/site-packages/optimus_manager/config.py", line 42, in validate_config
    corrected_config = copy.deepcopy(config)
  File "/usr/lib64/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object
```

**System info**
Please include :
- Gentoo
- KDE
- SDDM
- The version of optimus-manager you are using : the latest Git version (optimus-manager-git)

**Logs**
/var/log/optimus-manager/boot_setup.log
=================================
```shell
2019-09-29 03:07:49 PM +0800 ==================== 

Optimus Manager (Setup script) version 1.2.1
Setting up boot
Removing config copy
removing last acpi_call state (if any)
Copying user config
Error : attempting to run the initial boot setup while a X server is already running ! Skipping initial GPU setup.
```

**Comment by seewpx** [comment]
File "/usr/lib64/python3.6/site-packages/optimus_manager/config.py", line 42, in validate_config
    corrected_config = copy.deepcopy(config)
I change copy.deepcopy to copy.copy to make it run. I don't know if it break something.

**Comment by Askannz** [comment]
This error happens because you are using Gentoo and your Python version is 3.6 instead of 3.7.

It was easy enough to fix this time, but keep in mind that I can't really support distros that aren't Arch-based.

Should be fixed with the commit above, feel free to re-open otherwise.
