### ISSUE TITLE
TypeError in Log

### ISSUE THREAD

**Issue by mindrunner** [Askannz/optimus-manager#161]
**Describe the bug**
I just switched from `bbswitch` to `none`, to not use an external power manager for the nvidia card. It seems working alright, but I have a weird error in my log. (probably a bug)

I can switch back and forth all three modes without any issues. In intel mode, I do not see the NVidia card in `lspci` output, so I assume it is completely turned off, right?

**System info**
- Arch
- i3
- LightDM
- Lenovo ThinkPad W530
- aur/optimus-manager 1.2.1-1 (+18 3.46%) (Installed)

**Logs**
```
Optimus Manager (Setup script) version 1.2.1
Setting up boot
Removing config copy
removing last acpi_call state (if any)
Copying user config
Cleaning up leftover Xorg conf
Loading config
Reading startup mode
No kernel parameter set for startup, reading from file
Startup mode is : intel
Writing startup mode to requested GPU mode
Writing requested mode
Initial GPU setup
Checking for GDM display servers
Available kernel modules : ['nouveau', 'bbswitch', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset']
Setting up base state
Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia'] (if loaded)
Unloading modules ['nouveau'] (if loaded)
Running /etc/optimus-manager/nvidia-enable.sh
Unloading modules ['bbswitch'] (if loaded)
Setting up Intel state
Running /etc/optimus-manager/nvidia-disable.sh
Removing Nvidia from PCI bus
Traceback (most recent call last):
  File "/usr/bin/optimus-manager-setup", line 11, in <module>
    load_entry_point('optimus-manager==1.2.1', 'console_scripts', 'optimus-manager-setup')()
  File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_setup.py", line 63, in main
    _setup_gpu(config, startup_mode)
  File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_setup.py", line 181, in _setup_gpu
    setup_kernel_state(config, requested_mode)
  File "/usr/lib/python3.7/site-packages/optimus_manager/kernel.py", line 20, in setup_kernel_state
    _setup_intel_mode(config, available_modules)
  File "/usr/lib/python3.7/site-packages/optimus_manager/kernel.py", line 65, in _setup_intel_mode
    print("pci_remove is enabled, pci_power_control option ignored." % switching_mode)
TypeError: not all arguments converted during string formatting
```

**Comment by Askannz** [comment]
Yep, that's a bug alright. It actually crashes the whole script, so you're lucky that most of the setup is done by this point and optimus-manager is still usable.

Interesting tidbit : I normally rely on pylint to detect those kinds of errors, but it's completely missing this one.

After investigation, it appears that pylint only prints an error for `print("foo" % BAR)` when BAR is a hard-coded constant. That might be a bug.

**Comment by Askannz** [comment]
Fixed by the commit above.
