### ISSUE TITLE
UnboundLocalError after switching to `nvidia` mode

### ISSUE THREAD

**Issue by grzegorzk** [Askannz/optimus-manager#175]
I'm on ThinkPad P53 (which unfortunately I cannot use beyond hybrid mode). But while testing I was trying to switch to nvidia mode and each time after switch `optimus-manager --status` was resulting in below stack trace.

```python
Optimus Manager (Client) version 1.2.2

Error reading current mode : Cannot run glxinfo : Failed to execute 'glxinfo' : Error: unable to open display 
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 11, in <module>
    load_entry_point('optimus-manager==1.2.2', 'console_scripts', 'optimus-manager')()
  File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_client.py", line 75, in main
    _print_status()
  File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_client.py", line 205, in _print_status
    _print_current_mode()
  File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_client.py", line 164, in _print_current_mode
    print("Current GPU mode : %s" % mode)
UnboundLocalError: local variable 'mode' referenced before assignment
```

**Comment by Askannz** [comment]
Fixed by https://github.com/Askannz/optimus-manager/commit/b4d07c74c6445d794bf8f8928790826cc29b0230 already, will be included in next release. You can use the git version in the meantime.
