### ISSUE TITLE
(Probably fixed in master) 0.3-2 from the aur: Configuring anything in /etc/optimus-manager.conf makes lightdm crash during Xorg configuration

### ISSUE THREAD

**Issue by JpegXguy** [Askannz/optimus-manager#18]
journalctl -u lightdm

```Νοε 25 01:05:04 X555LD python[2925]: Optimus Manager (DM setup service) version 0.3
Νοε 25 01:05:04 X555LD python[2925]: Setting up Optimus configuration
Νοε 25 01:05:04 X555LD python[2925]: Cannot read requested mode : File /var/lib/optimus-manager/requested_mode not found..
Νοε 25 01:05:04 X555LD python[2925]: Using startup mode instead.
Νοε 25 01:05:04 X555LD python[2925]: Startup mode : intel
Νοε 25 01:05:04 X555LD python[2925]: Requested mode : intel
Νοε 25 01:05:04 X555LD python[2925]: Switching to Intel
Νοε 25 01:05:04 X555LD python[2925]: Unloading Nvidia modules
Νοε 25 01:05:05 X555LD python[2925]: Configuring Xorg...
Νοε 25 01:05:05 X555LD python[2925]: Traceback (most recent call last):
Νοε 25 01:05:05 X555LD python[2925]:   File "/usr/bin/optimus-manager-setup", line 11, in <module>
Νοε 25 01:05:05 X555LD python[2925]:     load_entry_point('optimus-manager==0.3', 'console_scripts', 'optimus-manager-setup')()
Νοε 25 01:05:05 X555LD python[2925]:   File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_setup.py", line 64, in main
Νοε 25 01:05:05 X555LD python[2925]:     switch_to_intel(config)
Νοε 25 01:05:05 X555LD python[2925]:   File "/usr/lib/python3.7/site-packages/optimus_manager/switching.py", line 51, in switch_to_intel
Νοε 25 01:05:05 X555LD python[2925]:     configure_xorg(config, mode="intel")
Νοε 25 01:05:05 X555LD python[2925]:   File "/usr/lib/python3.7/site-packages/optimus_manager/xorg.py", line 16, in configure_xorg
Νοε 25 01:05:05 X555LD python[2925]:     xorg_conf_text = _generate_intel(config, bus_ids)
Νοε 25 01:05:05 X555LD python[2925]:   File "/usr/lib/python3.7/site-packages/optimus_manager/xorg.py", line 57, in _generate_intel
Νοε 25 01:05:05 X555LD python[2925]:     text += "\tOption \"AccelMethod\" \"%d\"\n" % config["intel"]["accel"]
Νοε 25 01:05:05 X555LD python[2925]: TypeError: %d format: a number is required, not str
Νοε 25 01:05:05 X555LD systemd[1]: lightdm.service: Control process exited, code=exited status=1
```
In /etc/optimus-manager.conf I had
```
[intel]
driver=intel
accel=sna
tearfree=true
```

And I tried removing them one by one. Had to delete the file completely

**Comment by Askannz** [comment]
Yeah that's a bug, and it was still in master. Thank you for reporting it.
I'm going to push a new release to AUR soon, with the fix included.

**Comment by JpegXguy** [comment]
Everything works now, good work!
