### ISSUE TITLE
ac_auto not working and blocking change

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [Askannz/optimus-manager#238]
using ac_auto mode is buggy and trying to print the current mode or trying to change the mode
send an error about a previous error that prevented it to work and refuse to change the mode
and a path to a log file (wich's content i put at the end of this message)

i achieved to revert back to hybrid using the kernel parameter

my softwares:
Optimus Manager (Client) version 1.2.2
gdm-prime 3.34.1-1
nvidia-vulkan(developer branch) 440.66.08-2 (used for doom ethernal)
linux 5.6.2-arch1-2
```
cat /var/log/optimus-manager/switch/switch-20200407T153630.log
[11] INFO: # Xorg pre-start hook
[11] INFO: Requested mode is: ac_auto
[11] INFO: Checking for GDM display servers
[29] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/__init__.py", line 81, in setup_pre_xorg_start
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 15, in setup_kernel_state
    assert requested_mode in ["intel", "nvidia", "hybrid"]
AssertionError
[30] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[30] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200407T153630', 'requested_mode': 'ac_auto'}
```

**Comment by MaksVal** [comment]
I have too this problem.

**Comment by Askannz** [comment]
Well, at least the new logging system works :smile: 

Thanks, should be fixed now. Note that the `ac_auto` feature may change in the future (see https://github.com/Askannz/optimus-manager/issues/236).
