### ISSUE TITLE
Can't switch to Nvidia graphics in Manjaro

### ISSUE THREAD

**Issue by eatobin** [Askannz/optimus-manager#266]
Hello -

I listed this comment initially under #252 but have tried a fresh install with same results so felt I should open a new issue.

On Manjaro XFCE after an upgrade to 1.3 yesterday:

Here is the output from `systemctl status optimus-manager.service`:

```
● optimus-manager.service - Optimus Manager Commands Daemon
     Loaded: loaded (/usr/lib/systemd/system/optimus-manager.service; enabled; vendor preset: disabled)
     Active: active (running) since Mon 2020-06-01 15:39:38 CDT; 46min ago
    Process: 772 ExecStartPre=/usr/bin/python3 -u -m optimus_manager.hooks.pre_daemon_start (code=exited, status=0/SUCCESS)
    Process: 996 ExecStartPre=/usr/bin/python3 -u -m optimus_manager.hooks.pre_xorg_start (code=exited, status=0/SUCCESS)
   Main PID: 1009 (python3)
      Tasks: 1 (limit: 9452)
     Memory: 23.5M
     CGroup: /system.slice/optimus-manager.service
             └─1009 /usr/bin/python3 -u -m optimus_manager.daemon

Jun 01 15:39:38 linux-epth python3[996]: [907] INFO: Unloading modules ['nvidia_uvm', 'nvidia'] (if loaded)
Jun 01 15:39:38 linux-epth python3[996]: [1019] INFO: Loaded extra Intel Xorg options (0 lines)
Jun 01 15:39:38 linux-epth python3[996]: [1030] INFO: Loaded extra Intel Xorg options (0 lines)
Jun 01 15:39:38 linux-epth python3[996]: [1031] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
Jun 01 15:39:38 linux-epth python3[996]: [1031] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20200601T153937', 'requested_mode': 'intel'}
Jun 01 15:39:38 linux-epth python3[996]: [1059] INFO: Xorg pre-start hook completed successfully.
Jun 01 15:39:38 linux-epth systemd[1]: Started Optimus Manager Commands Daemon.
Jun 01 15:39:38 linux-epth python3[1009]: [3] INFO: # Commands daemon
Jun 01 15:39:38 linux-epth python3[1009]: [3] INFO: Opening UNIX socket
Jun 01 15:39:38 linux-epth python3[1009]: [3] INFO: Awaiting commands
```

All seems fine(?), until - the result of running `optimus-manager --status`:

```
[eric@linux-epth ~]$ optimus-manager --status
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 11, in exec_bash
    out = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', '__NV_PRIME_RENDER_OFFLOAD=0 glxinfo']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/checks.py", line 117, in _is_gl_provider_nvidia
    out = exec_bash("__NV_PRIME_RENDER_OFFLOAD=0 glxinfo")
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute '__NV_PRIME_RENDER_OFFLOAD=0 glxinfo' :
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  37
  Current serial number in output stream:  38
name of display: :0.0


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 11, in <module>
    load_entry_point('optimus-manager==1.3', 'console_scripts', 'optimus-manager')()
  File "/usr/lib/python3.8/site-packages/optimus_manager/client/__init__.py", line 24, in main
    fatal = report_errors(state)
  File "/usr/lib/python3.8/site-packages/optimus_manager/client/error_reporting.py", line 52, in report_errors
    active_renderer = get_active_renderer()
  File "/usr/lib/python3.8/site-packages/optimus_manager/checks.py", line 43, in get_active_renderer
    if _is_gl_provider_nvidia():
  File "/usr/lib/python3.8/site-packages/optimus_manager/checks.py", line 119, in _is_gl_provider_nvidia
    raise CheckError("Cannot run glxinfo : %s" % str(e))
optimus_manager.checks.CheckError: Cannot run glxinfo : Failed to execute '__NV_PRIME_RENDER_OFFLOAD=0 glxinfo' :
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  37
  Current serial number in output stream:  38
name of display: :0.0

[eric@linux-epth ~]$
```

I am stuck in Intel. Can not `optimus-manager --switch nvidia` - the result is same error.

What more could I provide to help troubleshoot this problem?

Thank you for your help and optimus-manager.

**Comment by Askannz** [comment]
I don't know the root cause of the issue yet, but there was a bug causing this error to not be properly handled. Try with the latest -git version, the error will still be there but it should point you to a log with more information. Please attach it here.

**Comment by eatobin** [comment]
Okay, but how do I obtain/install the -git version for you? I installed the original via `git clone https://aur.archlinux.org/optimus-manager.git` and `makepkg -sri`?

**Comment by Askannz** [comment]
https://aur.archlinux.org/packages/optimus-manager-git/

**Comment by eatobin** [comment]
I have installed the -git version and run `optimus-manager --status`:

```
[eric@linux-epth ~]$ optimus-manager --status
ERROR: cannot check the active card (should be "intel"). Reason: Cannot run glxinfo : Failed to execute '__NV_PRIME_RENDER_OFFLOAD=0 glxinfo' :
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  37
  Current serial number in output stream:  38
name of display: :0.0

Something went wrong during the last GPU setup...
Log at /var/log/optimus-manager/switch/switch-20200609T162154.log

Cannot execute command because of previous errors.
[eric@linux-epth ~]$
```

Attaching the referenced log here.

Is this helpful?

[switch-20200609T162154.log](https://github.com/Askannz/optimus-manager/files/4755005/switch-20200609T162154.log)

**Comment by Hyper-KVM** [comment]
Do you have glxinfo installed?

**Comment by eatobin** [comment]
Yes. I believe installed as part of mesa-demos 8.4.0 - which I do have installed. I could once run the gears...

**Comment by Hyper-KVM** [comment]
Does running `glxinfo` render the same error or does it operate as normal and returns the OpenGL info?

**Comment by Hyper-KVM** [comment]
Hmm, seems like the intel OpenGL driver is either broken or missing.

**Comment by eatobin** [comment]
```
eric@linux-epth ~]$ mhwd -l
> 0000:01:00.0 (0300:10de:06e5) Display controller nVidia Corporation:
--------------------------------------------------------------------------------
                  NAME               VERSION          FREEDRIVER           TYPE
--------------------------------------------------------------------------------
video-hybrid-intel-nvidia-340xx-bumblebee            2019.10.25               false            PCI
    video-nvidia-340xx            2019.10.25               false            PCI
           video-linux            2018.05.04                true            PCI
     video-modesetting            2020.01.13                true            PCI
            video-vesa            2017.03.12                true            PCI


> 0000:00:02.0 (0300:8086:2a42) Display controller Intel Corporation:
--------------------------------------------------------------------------------
                  NAME               VERSION          FREEDRIVER           TYPE
--------------------------------------------------------------------------------
video-hybrid-intel-nvidia-340xx-bumblebee            2019.10.25               false            PCI
           video-linux            2018.05.04                true            PCI
     video-modesetting            2020.01.13                true            PCI
            video-vesa            2017.03.12                true            PCI


[eric@linux-epth ~]$ mhwd -li
> Installed PCI configs:
--------------------------------------------------------------------------------
                  NAME               VERSION          FREEDRIVER           TYPE
--------------------------------------------------------------------------------
    video-nvidia-340xx            2019.10.25               false            PCI
           video-linux            2018.05.04                true            PCI


Warning: No installed USB configs!
[eric@linux-epth ~]$ glxinfo | grep OpenGL
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  37
  Current serial number in output stream:  38
[eric@linux-epth ~]$
```

Suggestions?

**Comment by eatobin** [comment]
Further info, if helpful:

```
[eric@linux-epth ~]$ inxi -Fxz
System:    Host: linux-epth Kernel: 5.4.43-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.1.0 Desktop: Xfce 4.14.2 
           Distro: Manjaro Linux 
Machine:   Type: Laptop System: Sony product: VGN-Z820G v: J0041B9W serial: <filter> 
           Mobo: Sony model: VAIO serial: <filter> BIOS: INSYDE v: R5031M3 date: 11/10/2009 
Battery:   ID-1: BAT0 charge: 25.2 Wh condition: 43.4/59.5 Wh (73%) model: Sony Corporation status: Charging 
CPU:       Topology: Dual Core model: Intel Core2 Duo P8700 bits: 64 type: MCP arch: Penryn rev: A L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 ssse3 vmx bogomips: 10113 
           Speed: 798 MHz min/max: 800/2534 MHz Core speeds (MHz): 1: 820 2: 830 
Graphics:  Device-1: Intel Mobile 4 Series Integrated Graphics vendor: Sony driver: i915 v: kernel bus ID: 00:02.0 
           Device-2: NVIDIA G98M [GeForce 9300M GS] vendor: Sony driver: N/A bus ID: 01:00.0 
           Display: x11 server: X.org 1.20.8 driver: modesetting resolution: <xdpyinfo missing> 
           OpenGL: renderer: N/A v: N/A direct render: N/A 
Audio:     Device-1: Intel 82801I HD Audio vendor: Sony driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
           Sound Server: ALSA v: k5.4.43-1-MANJARO 
Network:   Device-1: Intel 82567LM Gigabit Network vendor: Sony driver: e1000e v: 3.2.6-k port: 8100 bus ID: 00:19.0 
           IF: enp0s25 state: down mac: <filter> 
           Device-2: Intel WiFi Link 5100 driver: iwlwifi v: kernel port: 7000 bus ID: 06:00.0 
           IF: wlp6s0 state: up mac: <filter> 
Drives:    Local Storage: total: 298.09 GiB used: 106.17 GiB (35.6%) 
           ID-1: /dev/sda vendor: Hitachi model: HTS723232L9SA60 size: 298.09 GiB 
Partition: ID-1: / size: 283.75 GiB used: 106.17 GiB (37.4%) fs: ext4 dev: /dev/sda1 
           ID-2: swap-1 size: 8.80 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 44.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 217 Uptime: 24m Memory: 7.71 GiB used: 1.07 GiB (13.9%) Init: systemd Compilers: gcc: 10.1.0 Shell: bash 
           v: 5.0.17 inxi: 3.0.37 
[eric@linux-epth ~]$
```

**Comment by Hyper-KVM** [comment]
According to this, the nvidia driver is conflicting? I'm honestly lost here.
https://bbs.archlinux.org/viewtopic.php?id=243324

**Comment by Hyper-KVM** [comment]
I don't think this is a optimus-manager bug. Maybe you could try reinstalling the drivers but this is definitely bizarre.

**Comment by eatobin** [comment]
Thanks. I have previously done a force-reinstall of the Nvidia driver - no difference.

I am over my head here - drivers, mhwd, Archlinux, modesetting, xorg, LightDM, .conf, blacklist... I'm an intermediate Linux-er who is comfortable with the cli but I don't understand how all the graphics components move together - or conflict.

This time last month optimus-manager was working fine and switching between 2 graphics settings. The beginning of June I downloaded a 500+ package update from Manjaro and my problem began. But it wasn't because I changed anything - so I imagine other users are having the same problem with optimus-manager? What is the "bug" tag?

At this point I think I need the simplest, most basic graphics setup that will function with my hardware, get that working reliably and then layer up from there in small bites. I think that means booting into the Intel i915(?) environment without anything else running or installed - to see where that gets me.

Could you or @Askannz tell me or point me to how get to "square one" graphic-wise? [https://wiki.manjaro.org/Configure_Graphics_Cards](url) has been helpful but I can't figure out what is the most minimal setup there for my hardware.

Thank you.

**Comment by Hyper-KVM** [comment]
I would first uninstall optimus-manager and test using glxinfo to see if the same error occurs.

**Comment by Askannz** [comment]
> so I imagine other users are having the same problem with optimus-manager? What is the "bug" tag?

I tend to tag as "bug" everything that looks like a problem report - even if optimus-manager isn't really the cause. In this case you're the first to report such an issue, and I suspect that it's something broken in your configuration. As Hyper-KVM suggested, you should uninstall optimus-manager and try to at least get to a state where glxinfo works.

Just to be sure, `optimus-manager --print-mode` was working in both modes before the update, correct ?

You could also try reverting to v1.2.2 (just clone https://aur.archlinux.org/optimus-manager.git,  checkout an earlier commit, and `makepkg`), just to rule that out.
