### ISSUE TITLE
Can't switch from Intel to Hybrid/NVIDIA mode with nouveau.

### ISSUE THREAD

**Issue by yenson-lau** [Askannz/optimus-manager#276]
When I use `nouveau` as my switching method, I've noticed that whenever I switch over to the `intel` mode using `optimus-manager`, I can't switch back to `hybrid` or `nvidia` (it just logs out and stays in `intel` mode). Checking my logs from `/var/log/optimus-manager/switch/` tells me that the `nvidia` device is not there.

```
[5] INFO: # Xorg pre-start hook
[5] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'hybrid', 'current_mode': 'intel'}
[5] INFO: Requested mode is: hybrid
[5] INFO: Checking for GDM display servers
[81] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[81] INFO: Unloading modules ['nouveau'] (if loaded)
[1877] INFO: Loading module nvidia
[2287] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 11, in exec_bash
    out = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', 'modprobe nvidia NVreg_UsePageAttributeTable=1']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 179, in _load_module
    exec_bash("modprobe %s %s" % (module, options))
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' :
modprobe: ERROR: could not insert 'nvidia': No such device


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 45, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 21, in setup_kernel_state
    _nvidia_up(config)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 56, in _nvidia_up
    _load_nvidia_modules(config, available_modules)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 109, in _load_nvidia_modules
    _load_module(available_modules, "nvidia", options="NVreg_UsePageAttributeTable=%d" % pat_value)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 181, in _load_module
    raise KernelSetupError("error running modprobe for %s : %s" % (module, str(e)))
optimus_manager.kernel.KernelSetupError: error running modprobe for nvidia : Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' :
modprobe: ERROR: could not insert 'nvidia': No such device

[2289] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[2289] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200619T175836', 'requested_mode': 'hybrid'}
```

Is it impossible to do this switch because of how Nouveau works, or am I just missing something? I don't have NVIDIA's [RTD3](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/dynamicpowermanagement.html) enabled and my `optimus-manager.conf` looks like this:
```
[optimus]
switching=nouveau
pci_power_control=yes
pci_remove=no
pci_reset=no
auto_logout=yes
startup_mode=hybrid
startup_auto_battery_mode=intel
startup_auto_extpower_mode=hybrid

[intel]
driver=intel
accel=
tearfree=
DRI=3
modeset=yes

[nvidia]
modeset=yes
PAT=yes
DPI=96
ignore_abi=no
allow_external_gpus=no
options=overclocking
```

**Comment by yenson-lau** [comment]
Conversely if I try to change the switching method to `bbswitch`, trying to switch from `hybrid` to `intel` leads to the following error:
```
[6] INFO: # Xorg pre-start hook
[6] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'intel', 'current_mode': 'hybrid'}
[6] INFO: Requested mode is: intel
[6] INFO: Checking for GDM display servers
[209] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[209] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[211] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 11, in exec_bash
    out = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 196, in _unload_modules
    exec_bash("modprobe -r " + " ".join(modules_to_unload))
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia_drm is in use.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 45, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 24, in setup_kernel_state
    _nvidia_down(config)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 65, in _nvidia_down
    _unload_nvidia_modules(available_modules)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 148, in _unload_nvidia_modules
    _unload_modules(available_modules, ["nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nvidia"])
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 198, in _unload_modules
    raise KernelSetupError("Cannot unload modules %s : %s" % (str(modules_to_unload), str(e)))
optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia_drm is in use.

[212] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[212] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200620T004230', 'requested_mode': 'intel'}
```

**Comment by yenson-lau** [comment]
After a bunch of experiments I've settled on
```
[optimus]
switching=none
pci_power_control=yes
pci_remove=yes
pci_reset=no
auto_logout=yes
startup_mode=hybrid
startup_auto_battery_mode=intel
startup_auto_extpower_mode=hybrid
```
This seems to provide the most stability in allowing me to switch back and forth between `intel` and `hybrid`, whilst allowing for the GPU to be turned off in `intel` mode. Not much PM happening on `hybrid` mode though. For that [RTD3](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/dynamicpowermanagement.html) seems to be the best way but it leads to a lot of weird / worrying behaviour... not worth it so far.

**Comment by Askannz** [comment]
Yeah, unfortunately nouveau has iffy support at best and does not co-exist very well with the official driver. It causes similar issues in my laptop as well.

I don't really have a solution to offer, but the best way to deal with power management in general is to do what you did and play around with config parameters until you find something stable enough.
