### ISSUE TITLE
Start Intel (OK); Switch NVIDIA (OK); Switch Intel (OK); no more switching: modprobe: FATAL: Module nvidia is in use.

### ISSUE THREAD

**Issue by AndydeCleyre** [Askannz/optimus-manager#277]
**Describe the bug**
Thanks for this project! I'm switching from bumblebee.

I can switch from Intel to NVIDIA and back to Intel once more, but the `nvidia` module doesn't get unloaded, and `optimus-manager` won't do anything more, complaining that the Xorg pre-start hook failed (logs below).

**System info**
- Arch Linux
- KDE Plasma
- SDDM
- optimus-manager 1.3
- `/etc/optimus-manager/optimus-manager.conf` (I think this is still as default):

```ini
[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=
[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=no
modeset=yes
options=overclocking
[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=intel
startup_auto_extpower_mode=nvidia
startup_mode=intel
switching=none
```

**Logs**

```console
$ optimus-manager --status
ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20200621T142717.log

Cannot execute command because of previous errors.
```

Best of `/var/log/optimus-manager/switch/switch-20200621T142717.log`:

```
subprocess.CalledProcessError: Command '['bash', '-c', 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia']' returned non-zero exit status 1.
optimus_manager.bash.BashError: Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.
optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.
```

<details><summary>Full log</summary>

<p>

```
[10] INFO: # Xorg pre-start hook
[10] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'intel', 'current_mode': 'nvidia'}
[10] INFO: Requested mode is: intel
[10] INFO: Checking for GDM display servers
[890] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[890] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[916] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 11, in exec_bash
    out = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 196, in _unload_modules
    exec_bash("modprobe -r " + " ".join(modules_to_unload))
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 45, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 24, in setup_kernel_state
    _nvidia_down(config)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 65, in _nvidia_down
    _unload_nvidia_modules(available_modules)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 148, in _unload_nvidia_modules
    _unload_modules(available_modules, ["nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nvidia"])
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 198, in _unload_modules
    raise KernelSetupError("Cannot unload modules %s : %s" % (str(modules_to_unload), str(e)))
optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.

[917] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[918] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200621T142717', 'requested_mode': 'intel'}
```

</p>

</details>

In this second Intel session:

```console
$ lsmod | grep -i nvid
nvidia              20520960  0
ipmi_msghandler        77824  2 ipmi_devintf,nvidia
$ sudo modprobe -r nvidia
$ lsmod | grep -i nvid
$ pacman -Qqs nvidia
egl-wayland
lib32-libvdpau
lib32-nvidia-utils
lib32-opencl-nvidia
libvdpau
nvidia-dkms
nvidia-utils
opencl-nvidia
```

**SDDM Configs**

`/etc/sddm.conf.d/20-optimus-manager.conf`:
```ini
[X11]
DisplayCommand=/sbin/prime-offload
DisplayStopCommand=/sbin/prime-switch
```

`/etc/sddm.conf.d/kde_settings.conf`:
```ini
[Autologin]
Relogin=false
Session=
User=andy

[General]
HaltCommand=/usr/bin/systemctl poweroff
Numlock=on
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=breeze
CursorTheme=breeze_cursors

[Users]
MaximumUid=60000
MinimumUid=1000

[X11]
ServerArguments=-dpi 0
```

`/etc/sddm.conf`:
```ini
[General]
InputMethod=

[Theme]
DisableAvatarsThreshold=7
EnableAvatars=true
FacesDir=/usr/share/sddm/faces
ThemeDir=/usr/share/sddm/themes

[Users]
DefaultPath=/bin:/usr/bin:/usr/local/bin
HideShells=
HideUsers=
RememberLastSession=true
RememberLastUser=true
ReuseSession=false

[Wayland]
EnableHiDPI=false
SessionCommand=/usr/share/sddm/scripts/wayland-session
SessionDir=/usr/share/wayland-sessions
SessionLogFile=.local/share/sddm/wayland-session.log

[X11]
# DisplayCommand=/usr/share/sddm/scripts/Xsetup
# DisplayStopCommand=/usr/share/sddm/scripts/Xstop
EnableHiDPI=false
MinimumVT=1
ServerPath=/usr/bin/X
SessionCommand=/usr/share/sddm/scripts/Xsession
SessionDir=/usr/share/xsessions
SessionLogFile=.local/share/sddm/xorg-session.log
UserAuthFile=.Xauthority
XauthPath=/usr/bin/xauth
XephyrPath=/usr/bin/Xephyr
```

**Comment by dgaus** [comment]
I am having a similar issue on my Lenovo X1 extreme, used to work fine with bbswitch and `pci_reset=function_level` but after some recent updates it's failing to unload the nvidia module. Please let me know if I can help debug this, thanks.

**Comment by linasdev** [comment]
I am having the same issue, switching from nvidia mode fails to unload the nvidia module. If I kill sddm while in nvidia mode, I can successfully unload all nvidia modules with `modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia`. The same command works after switching to intel mode (same as @dgaus).

**Comment by linasdev** [comment]
Okay, this is awkward... I fixed it but I have no clue what I did (hate when this happens). The last thing I did was modify `/usr/lib/python3.8/site-packages/optimus_manager/kernel.py` and add `exec_bash("lsmod > /tmp/before_switch.log")` just before the call to `modprobe -r` so I could sanity check that the nvidia module was being used and couldn't be unloaded. I found that it wasn't being used and it's now working. I might at some point try a fresh install and try to retrace my steps so I could help @AndydeCleyre and @dgaus but for now, this 5+ hour debug session has killed me and I'm done with this.

Just in case it might help you guys, here's my config files:
`/etc/optimus-manager/optimus-manager.conf`:
```
[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=hybrid
startup_auto_extpower_mode=nvidia
startup_mode=auto
switching=bbswitch
```
`/etc/sddm.conf.d/20-optimus-manager.conf` (I did mess with this before but this is the default):
```
[X11]
DisplayCommand=/sbin/prime-offload
DisplayStopCommand=/sbin/prime-switch
```

I'm using  v1.3 of `optimus-manager` (currently the latest from AUR) and also v1.5.2 of `optimus-manager-qt`.

**Comment by Askannz** [comment]
Late reply, but yeah, I know module unloading is wonky. It's an issue that I can sporadically reproduce on my machine too. There must be some kind of race condition where the optimus-manager hook is called before X is done with the nvidia driver. It would explain why adding a simple `lsmod` is enough to hide the issue, since you're basically adding a small delay before the module unloading.

I'll look into putting a synchronization point to loop over `modprobe -r` with a delay, and try a few times before giving up. It's kind of a hack though, the proper way would be to check which programs are still hanging to the GPU, but I don't know how to do that.

**Comment by linasdev** [comment]
@Askannz  Can agree that this is probably some kind of race condition.
SDDM's man page says:
```
DisplayStopCommand=
    Path of script to execute when stopping the display server. Default value is "/usr/share/sddm/scripts/Xstop". 
```
Does this mean after stopping X or after "beginning" to stop X? If it is the latter, maybe trying other DM's would help diagnose the problem?
In any case maybe using something like `nvidia-smi -q -d PIDS | grep -oP "^\s+Process ID\s+:\s+\K[0-9]+"` would be enough to find processes preventing the driver to be unloaded?

**Comment by linasdev** [comment]
Okay, I tried something like this:
```
def _unload_modules(available_modules, modules_list):

    logger = get_logger()

    modules_to_unload = [m for m in modules_list if m in available_modules]

    if len(modules_to_unload) == 0:
        return

    logger.info("Unloading modules %s (if loaded)", str(modules_to_unload))

    try:
        loaded_modules = exec_bash("lsmod")

        regex = r"^(?:%s\s+)[0-9]+\s+([0-9]+)" % r"\s+|".join(modules_to_unload)

        for _ in range(10):
            used_by = findall(regex, loaded_modules, MULTILINE)
            used_by = sum([int(x) for x in used_by])

            if used_by > 0:
                regex2 = r"^(%s\s+)[0-9]+\s+([0-9]+)" % r"\s+|".join(modules_to_unload)
                used_by2 = findall(regex2, loaded_modules, MULTILINE)

                logger.info(" ".join(used_by2))
                logger.info(exec_bash("nvidia-smi"))
                logger.info(exec_bash("pgrep Xorg"))
                logger.info("Some of the targeted modules are still in use, trying again in 0.5s")
                sleep(0.1)
                continue
            
            break

        # Unlike "rmmod", "modprobe -r" does not return an error if the module is not loaded.
        exec_bash("modprobe -r " + " ".join(modules_to_unload))
    except BashError as e:
        raise KernelSetupError("Cannot unload modules %s : %s" % (str(modules_to_unload), str(e)))
```
It seems that at the time of unloading the X server is already dead and no processes are reported by `nvidia-smi` but the kernel modules are still being used by something (`nvidia_drm`, `nvidia_modeset` and `nvidia` in my case).

**Comment by bjsowa** [comment]
I have the same error on optimus-manager from `amd_support` branch when switching from `nvidia` to `integrated`

**Comment by Askannz** [comment]
I went for a slightly cleaner approach: https://github.com/Askannz/optimus-manager/commit/42fb3c9208ddb848385ba380ce4c9a577e6ccec5

optimus-manager now uses the Nvidia Management Library (NVML) to check for processes holding the Nvidia GPU, and checks a few times for all the processes to exit before giving up. It's functionally the same as retrying `modprobe -r`, except that it shows in the logs which process is holding the card.

I'd appreciate if someone who was experiencing the issue could test that solution :slightly_smiling_face: (Note that it adds 2 dependencies to the package, `python-py3nvml` and `python-psutil`. Both can be found in AUR)

**Comment by AndydeCleyre** [comment]
I tested again with master @ [gc579b7b](c579b7b6c382ebf761aba96e36f2f3fce83bff63), but it looks like it's still surprised by modules in use:

<details><summary>/var/log/optimus-manager/switch/switch-20200921T125325.log:</summary>

<p>

```
[30] INFO: # Xorg pre-start hook
[30] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'intel', 'current_mode': 'nvidia'}
[30] INFO: Requested mode is: intel
[30] INFO: Checking for GDM display servers
[789] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[796] INFO: No processes currently holding the Nvidia GPU
[796] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[832] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 11, in exec_bash
    out = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 230, in _unload_modules
    exec_bash("modprobe -r " + " ".join(modules_to_unload))
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 45, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 25, in setup_kernel_state
    _nvidia_down(config)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 67, in _nvidia_down
    _unload_nvidia_modules(available_modules)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 182, in _unload_nvidia_modules
    _unload_modules(available_modules, ["nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nvidia"])
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 232, in _unload_modules
    raise KernelSetupError("Cannot unload modules %s : %s" % (str(modules_to_unload), str(e)))
optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.

[833] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[833] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200921T125325', 'requested_mode': 'intel'}

```

</p>

</details>

**Comment by andryandrew** [comment]
Same here, while with 1.3.1 it fails early on at unloading `nvidia_drm`, with current master it unloads almost everything but still fails for `nvidia`. My log is the same as @AndydeCleyre

**Comment by leledumbo** [comment]
Having the same problem, let me join the party. As an additional info, even after manually unloading nvidia module, it still refuses to switch to nvidia referring that there was a problem in last switching. Restarting the daemon and wait for some time (not sure how long, just for sure cannot be done immediately) allows the switching. Weird, eh?

**Comment by ljtnono** [comment]
Is this issue resolved now?

**Comment by nwildner** [comment]
That is a good question @ljtnono . Were you able to test it?
Also, could this be related with the `nvidia-powerd` case where it is hold modules surrogate to it? - last comment of #477
