### ISSUE TITLE
ERROR: the optimus-manager service failed boot-time startup.

### ISSUE THREAD

**Issue by Fuxino** [Askannz/optimus-manager#283]
I'm currently unable to run optimus-manager, `optimus-manager --status` gives the following error:

```
ERROR: the optimus-manager service failed boot-time startup.
Log at /var/log/optimus-manager/daemon/daemon-20200704T185000.log
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 33, in <module>
    sys.exit(load_entry_point('optimus-manager==1.3', 'console_scripts', 'optimus-manager')())
  File "/usr/lib/python3.8/site-packages/optimus_manager/client/__init__.py", line 26, in main
    config = _get_config()
  File "/usr/lib/python3.8/site-packages/optimus_manager/client/__init__.py", line 103, in _get_config
    config = load_config()
  File "/usr/lib/python3.8/site-packages/optimus_manager/config.py", line 30, in load_config
    user_config.read([envs.DEFAULT_CONFIG_PATH, envs.USER_CONFIG_COPY_PATH])
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.8/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/var/lib/optimus-manager/tmp/config_copy.conf' [line 20]: option 'pci_remove' in section 'optimus' already exists
```

I'm running Arch Linux with the latest kernel (i.e. 5.7.7), no desktop manager, Openbox as window manaer, and LightDM as display manager.
I'm using the latest Git version of optimus-manager.

Thanks for any help.

EDIT: Same issue with non-Git version of optimus-manager and with LTS kernel (i.e. 5.4.50)

**Comment by Askannz** [comment]
What's your optimus-manager configuration file ?

**Comment by Fuxino** [comment]
Hi, this is my config file (`/etc/optimus-manager/optimus-manager.conf`):

```
[intel]
DRI=3
accel=
driver=intel
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
pci_remove=no.
auto_logout=yes
pci_power_control=yes
pci_remove=no
pci_reset=no
startup_auto_battery_mode=intel
startup_auto_extpower_mode=nvidia
startup_mode=nvidia
switching=none
```

**Comment by Askannz** [comment]
`pci_remove` is specified twice. Try removing the one under `[optimus]` (it seems to have an extra `.` as well).

**Comment by Fuxino** [comment]
Ah, weird, no idea how that happened. But that seemed to be the problem indeed, working fine now. Thanks :+1:

**Comment by Askannz** [comment]
FYI, you don't have to specify every option. If you don't specify an option in `/etc/optimus-manager/optimus-manager.conf`, the default value from `/usr/share/optimus-manager.conf` will be used instead.
