### ISSUE TITLE
Unable to switch to nvidia

### ISSUE THREAD

**Issue by prashunchitkr** [Askannz/optimus-manager#299]
Kernel: 5.7.10-arch1-1
Optimus Manager version: 1.3.1-1
Nvidia driver version: 450.57-4
bbswitch version: 0.8-334

I am currently unable to switch to nvidia with switching set to **bbswitch** (also tried other methods no luck) but can switch using switching method set to **none**

Last thing i remember installing was [nvidia-container-toolkit](https://aur.archlinux.org/packages/nvidia-container-toolkit/) which I now have uninstalled

Logs: 

```
[17] INFO: # Xorg pre-start hook
[18] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': 'intel'}
[18] INFO: Requested mode is: nvidia
[18] INFO: Checking for GDM display servers
[32] WARNING: Config parsing : unknown option "ac_auto_battery_mode" in section [optimus]. Ignoring.
[880] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[881] INFO: Unloading modules ['nouveau'] (if loaded)
[883] INFO: Loading module bbswitch
[886] INFO: Setting GPU power to ON via bbswitch
[1445] INFO: Loading module nvidia
[2304] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 11, in exec_bash
    out = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', 'modprobe nvidia NVreg_UsePageAttributeTable=1']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 179, in _load_module
    exec_bash("modprobe %s %s" % (module, options))
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' :
modprobe: ERROR: could not insert 'nvidia': No such device


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 45, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 21, in setup_kernel_state
    _nvidia_up(config)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 56, in _nvidia_up
    _load_nvidia_modules(config, available_modules)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 109, in _load_nvidia_modules
    _load_module(available_modules, "nvidia", options="NVreg_UsePageAttributeTable=%d" % pat_value)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 181, in _load_module
    raise KernelSetupError("error running modprobe for %s : %s" % (module, str(e)))
optimus_manager.kernel.KernelSetupError: error running modprobe for nvidia : Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' :
modprobe: ERROR: could not insert 'nvidia': No such device

[2305] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[2305] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200728T223537', 'requested_mode': 'nvidia'}
```

**Comment by prashunchitkr** [comment]
FIxed
powertop was found to be the culprit not letting letting powering on the nvidia GPU
