### ISSUE TITLE
Black laptop screen

### ISSUE THREAD

**Issue by deathwaiting** [Askannz/optimus-manager#305]
i recently installed optimus-manager on lenovo legion 5 laptop, with amd integrated graphic card and nvidia 1650 as discrete module.

running optimus-manager gives

`ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20200809T052445.log

Cannot execute command because of previous errors.`

logs:
`[11] INFO: # Xorg pre-start hook
[11] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'intel', 'current_mode': None}
[11] INFO: Requested mode is: intel
[11] INFO: Checking for GDM display servers
[232] INFO: Available modules: ['nouveau', 'bbswitch', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[232] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[252] INFO: Loaded extra Intel Xorg options (0 lines)
[253] INFO: Loaded extra Intel Xorg options (0 lines)
[254] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 46, in main
    configure_xorg(config, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/xorg.py", line 23, in configure_xorg
    xorg_conf_text = _generate_intel(config, bus_ids, xorg_extra)
  File "/usr/lib/python3.8/site-packages/optimus_manager/xorg.py", line 150, in _generate_intel
    text = _make_intel_device_section(config, bus_ids, xorg_extra)
  File "/usr/lib/python3.8/site-packages/optimus_manager/xorg.py", line 218, in _make_intel_device_section
    text += "\tBusID \"%s\"\n" % bus_ids["intel"]
KeyError: 'intel'
[254] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[254] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200809T052445', 'requested_mode': 'intel'}
`

**Comment by deathwaiting** [comment]
i replaced optimus-manager with this [fork](https://aur.archlinux.org/packages/optimus-manager-amd-git)
which seems to use this [PR](https://github.com/Askannz/optimus-manager/pull/268).

both screens are now working on nvidia mode, but still have some sluggish response and sometimes switching to nvidia mode seems to crash the display manager after auto re-login.

**Comment by Askannz** [comment]
Sorry, laptops with AMD iGPUs are not supported yet. I plan on adding that soon.
