### ISSUE TITLE
py3nvml driver not loaded when running optimus-manager

### ISSUE THREAD

**Issue by evancholmberg** [Askannz/optimus-manager#335]
When I try to start the optimus-manager service or switch to a different graphics mode, I get an error saying py3nvml was not loaded. I tried manually installing py3nvml but that did not seem to help. I also reinstalled `nvidia-dkms`, `nvidia-utils`, `nvidia-settings`, and `nvidia-prime`.  

**System info**
Please include :
- Arch
- Gnome
- GDM
- Asus Zephyrus g14 GA401I
- version 1.3.1

**Logs**
`optimus-manager --status` output
`ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20201022T201006.log
Cannot execute command because of previous errors.`
The log file contains 
`26] INFO: # Xorg pre-start hook
[26] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[26] INFO: Requested mode is: integrated
[27] INFO: Checking for GDM display servers
[810] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[848] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 45, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 25, in setup_kernel_state
    _nvidia_down(config)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 100, in _nvidia_down
    _wait_no_processes_on_nvidia()
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 181, in _wait_no_processes_on_nvidia
    processes_list = checks.list_processes_on_nvidia()
  File "/usr/lib/python3.8/site-packages/optimus_manager/checks.py", line 121, in list_processes_on_nvidia
    nvml.nvmlInit()
  File "/usr/lib/python3.8/site-packages/py3nvml/py3nvml.py", line 1093, in nvmlInit
    _nvmlCheckReturn(ret)
  File "/usr/lib/python3.8/site-packages/py3nvml/py3nvml.py", line 719, in _nvmlCheckReturn
    raise NVMLError(ret)
py3nvml.py3nvml.NVMLError_DriverNotLoaded: Driver Not Loaded
[852] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[852] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20201022T201006', 'requested_mode': 'integrated'}`

**Comment by Askannz** [comment]
I removed the dependency on py3nvml, that should fix the issue.
