### ISSUE TITLE
start-pre operation timed out

### ISSUE THREAD

**Issue by FPSUsername** [Askannz/optimus-manager#348]
**Describe the bug**
Booting the laptop results in a start job for optimus-manager. The timeout increases to ~6 minutes before finally reaching the graphical UI.
Shutting down the laptop result in a endless wait for python3

**System info**
- Manjaro with kernel 5.9.11-3-MANJARO
- KDE Plasma 5.20.3 (Manjaro testing repositories)
- SDDM
- Dell XPS15 9560
- optimus-manager-git (1.3.1.r42.g831abd8-1)
- Optimus-manager config:
```
[intel]
DRI=3
accel=
driver=intel
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=integrated
startup_auto_extpower_mode=nvidia
startup_mode=integrated
switching=none
```

**Logs**
```
● optimus-manager.service - Optimus Manager Commands Daemon
     Loaded: loaded (/usr/lib/systemd/system/optimus-manager.service; enabled; vendor preset: disabled)
     Active: failed (Result: timeout) since Tue 2020-12-01 10:56:17 CET; 1min 23s ago
    Process: 487 ExecStartPre=/usr/bin/python3 -u -m optimus_manager.hooks.pre_daemon_start (code=exited, status=0/SUCCESS)
    Process: 998 ExecStopPost=/usr/bin/python3 -u -m optimus_manager.hooks.post_daemon_stop (code=exited, status=0/SUCCESS)

Dec 01 10:50:17 xps-15 systemd[1]: Starting Optimus Manager Commands Daemon...
Dec 01 10:50:17 xps-15 python3[598]: [79] INFO: # Daemon pre-start hook
Dec 01 10:50:17 xps-15 python3[598]: [79] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
Dec 01 10:50:17 xps-15 python3[598]: [81] INFO: Copying /etc/optimus-manager/optimus-manager.conf to /var/lib/optimus-manager/tmp/config_copy.conf
Dec 01 10:50:17 xps-15 python3[598]: [84] INFO: Startup mode is: integrated
Dec 01 10:50:17 xps-15 python3[598]: [84] INFO: Writing state {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
Dec 01 10:50:17 xps-15 python3[598]: [84] INFO: Daemon pre-start hook completed successfully.
Dec 01 10:50:17 xps-15 python3[598]: [84] INFO: Calling Xorg pre-start hook.
Dec 01 10:50:17 xps-15 python3[672]: [28] INFO: # Xorg pre-start hook
Dec 01 10:50:17 xps-15 python3[672]: [28] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
Dec 01 10:50:17 xps-15 python3[672]: [28] INFO: Requested mode is: integrated
Dec 01 10:50:17 xps-15 python3[672]: [28] INFO: Checking for GDM display servers
Dec 01 10:50:17 xps-15 python3[601]: [325] INFO: Available modules: ['nouveau', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
Dec 01 10:51:47 xps-15 systemd[1]: optimus-manager.service: start-pre operation timed out. Terminating.
Dec 01 10:53:17 xps-15 systemd[1]: optimus-manager.service: State 'stop-sigterm' timed out. Killing.
Dec 01 10:53:17 xps-15 systemd[1]: optimus-manager.service: Killing process 601 (python3) with signal SIGKILL.
Dec 01 10:54:47 xps-15 systemd[1]: optimus-manager.service: Processes still around after SIGKILL. Ignoring.
Dec 01 10:56:17 xps-15 systemd[1]: optimus-manager.service: State 'final-sigterm' timed out. Killing.
Dec 01 10:56:17 xps-15 systemd[1]: optimus-manager.service: Killing process 601 (python3) with signal SIGKILL.
Dec 01 10:56:17 xps-15 systemd[1]: optimus-manager.service: Failed with result 'timeout'.
Dec 01 10:56:17 xps-15 systemd[1]: optimus-manager.service: Unit process 601 (python3) remains running after unit stopped.
Dec 01 10:56:17 xps-15 systemd[1]: Failed to start Optimus Manager Commands Daemon.
```

`optimus-manager --status` returns:
`ERROR: no state file found. Is optimus-manager.service running ?`

**Notes**
I have custom settings for `nvidia-enable.sh`:
```
echo '\_SB.PCI0.PEG0.PEGP._ON' | sudo tee --append /proc/acpi/call > /dev/null
sudo rmmod acpi_call
sleep 5
```

And `nvidia-disable.sh`:
```
sleep 5
sudo modprobe acpi_call
sleep 10
echo '\_SB.PCI0.PEG0.PEGP._OFF' | sudo tee --append /proc/acpi/call >/dev/null
```

This is my workaround for issue #331

**Comment by FPSUsername** [comment]
I managed to start it manually. `optimus-manager --status` returns:
```
ERROR: a GPU setup was initiated but Xorg pre-start hook did not run.
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 33, in <module>
    sys.exit(load_entry_point('optimus-manager==1.3', 'console_scripts', 'optimus-manager')())
  File "/usr/lib/python3.8/site-packages/optimus_manager/client/__init__.py", line 24, in main
    fatal = report_errors(state)
  File "/usr/lib/python3.8/site-packages/optimus_manager/client/error_reporting.py", line 19, in report_errors
    print("Log at %s/switch/switch-%s.log" % (envs.LOG_DIR_PATH, state["switch_id"]))
KeyError: 'switch_id'

```

**Comment by nwildner** [comment]
Hello. Since this case is almost 4 years old, we'll be closing it.

Please update your distribution and keep track of `optimus-manager-git` .
