### ISSUE TITLE
Optimus manager crashes when system upgrades to python 3.9

### ISSUE THREAD

**Issue by Szybet** [Askannz/optimus-manager#349]
After system upgrade, on Arch optimus manager crashes, so any GUI is not working. I needed to reinstall optimus-manager to get it working again.
Its becouse Arch upgraded to python 3.9 and optimus manager doesnt know it, and looks at 3.8 libraries.

Im sharing this becouse there can by other issues with this problem, when only whots needed is reintall.
Maybe push a update to avoid that?
Also journalctl -xe, or dmesg didnt show anything related to this. a bit strange. But the status of services says the problem.

journalctl -u optimus-manager -xe:

`gru 02 21:38:27 ArchSzybet python3[855]: /usr/bin/python3: Error while finding module specification for 'optimus_manager.hooks.post_da>
gru 02 21:38:27 ArchSzybet systemd[1]: optimus-manager.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Proces jednostki zakończył działanie
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ Proces ExecStopPost= należący do jednostki optimus-manager.service zakończył działanie.
░░ 
░░ Kod wyjścia procesu: „exited”, jego stan wyjścia: 1.`

**Comment by rharish101** [comment]
Please rebuild the package from the AUR. It will then use Python 3.9 instead of Python 3.8. I faced this same error, and rebuilding the package fixed it.

Credits: [LIN_X42](https://aur.archlinux.org/account/LIN_X42)'s comment on the [AUR page for optimus-manager](https://aur.archlinux.org/packages/optimus-manager/).

**Comment by kevindirect** [comment]
I had to chroot into my system, disable lightdm, and update the system to be able to get xorg working properly.
Once I could log into a graphical session, I reinstalled optimus manager, cleaned up stale system config files (optimus-manager --clean) and then enabled lightdm again. This worked for me.

**Comment by kevindirect** [comment]
Is there a way to prevent this from happening when python is updated again? Maybe grab the python version at boot when the optimus manager service starts so it just requires a reboot to work again.

**Comment by Szybet** [comment]
The best you can do is reinstall all AUR packages, not only for python after a system upgrade

**Comment by Szybet** [comment]
with yay:
pacman -Qmq | yay --rebuild -S -

**Comment by kevindirect** [comment]
I was thinking of something that was automated or an update to the actual package.
A pacman hook that rebuilds optimus manager whenever one of its dependencies is updated would be a simple solution, but updating the actual package somehow would be ideal.

I don't know enough about optimus manager to know why rebuilding is necessary. Wouldn't it be enough to restart the optimus-manager service after a dependency is updated? Or couldn't the service find the right python version when it's initialized (so all you need is a reboot to fix the problem)?

**Comment by kevindirect** [comment]
I wonder if something like this would work as a pacman hook to prevent future problems:

```
[Trigger]
Type = Package
Operation = Install
Operation = Upgrade
Target = Python <other dependencies here...>

[Action]
Description = Rebuilding Optimus Manager because a dependency was upgraded
When = PostTransaction
Exec = yay -S optimus-manager <IDK if you can exec yay/pacman within a pacman hook>
Exec = systemctl restart optimus-manager.service <Would this work instead?>
```

**Comment by alx365** [comment]
a hook would be pretty nice.. i've spent an hour on this problem before i found this issue

**Comment by limelier** [comment]
It took me a few days to figure out why updating (a whole bunch of stuff including) python broke my entire system. It would be pretty cool if this didn't happen in the future.

**Comment by Szybet** [comment]
Yes i said that, there will be problems with that
the easiest way is to push a empty update to rebuild it

**Comment by ChiragSukhala** [comment]
found this after 2hours of debugging. I was suspecting Xorg for no GUI or diplay after update but it was Optimus. Automatic rebuild or some other fixes will be appreciated.

**Comment by kennyfh** [comment]
> with yay:
> pacman -Qmq | yay --rebuild -S -

It works, thank you

**Comment by andrfgs** [comment]
Rebuilding does not work. I tried rebuilding and it still has this bug. This is either a Python 3.9 problem or a bug in the 1.3 version

**Comment by Kr1ss-XD** [comment]
@andrfgs This might sound trivial, but did you actually update the package after rebuilding ?  How did you rebuild (which command(s) did you run) ?

**Comment by andrfgs** [comment]
I used `yay -R optimus-manager` followed by `yay -S optimus-manager`, when installing I chose to recompile everything from source, which yay does by removing the cached version and by reinstalling.

Now my computer seems to be in Intel mode. I can read the GPU temperature sensor but `nvidia-settings` is not working. 

This is the log of optimus manager (which is similar to the one posted above):
```
[27] INFO: # Xorg pre-start hook
[27] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[27] INFO: Requested mode is: integrated
[905] INFO: Available modules: ['nouveau', 'bbswitch', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[947] INFO: No processes currently holding the Nvidia GPU
[947] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[950] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/bash.py", line 11, in exec_bash
    out = subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 255, in _unload_modules
    exec_bash("modprobe -r " + " ".join(modules_to_unload))
  File "/usr/lib/python3.9/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 51, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 25, in setup_kernel_state
    _nvidia_down(config)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 101, in _nvidia_down
    _unload_nvidia_modules(available_modules)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 207, in _unload_nvidia_modules
    _unload_modules(available_modules, ["nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nvidia"])
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 257, in _unload_modules
    raise KernelSetupError("Cannot unload modules %s : %s" % (str(modules_to_unload), str(e)))
optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.

[951] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[951] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20210104T174910', 'requested_mode': 'integrated'}
```

This log makes no sense as there are no processes holding the GPU and I have manually and successfully ran:
`> sudo modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia`

To be honest, I'd like to know how to help with this because this tool is incredibly helpful to me and I thank the developer for all the work!

**Comment by Kr1ss-XD** [comment]
Thx for getting back.

`yay -R optimus-manager; yay -S optimus-manager` does not actually rebuild the package. It uninstalls it and reinstalls the old package from your pacman cache.

I _think_ `yay` has a `--rebuild` flag or something similar though. Not really sure what it exactly is, because I'm not a yay user. Might also be `--cleanbuild`, check the docs.

**Comment by andrfgs** [comment]
I used `yay -R optimus-manager` followed by `yay -S optimus-manager`, when installing I chose to recompile everything from source, which yay does by removing the cached version and by reinstalling.

Now my computer seems to be in Intel mode. I can read the GPU temperature sensor but `nvidia-settings` is not working. 

This is the log of optimus manager (which is similar to the one posted above):
```
[27] INFO: # Xorg pre-start hook
[27] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[27] INFO: Requested mode is: integrated
[905] INFO: Available modules: ['nouveau', 'bbswitch', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[947] INFO: No processes currently holding the Nvidia GPU
[947] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[950] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/bash.py", line 11, in exec_bash
    out = subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 255, in _unload_modules
    exec_bash("modprobe -r " + " ".join(modules_to_unload))
  File "/usr/lib/python3.9/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 51, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 25, in setup_kernel_state
    _nvidia_down(config)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 101, in _nvidia_down
    _unload_nvidia_modules(available_modules)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 207, in _unload_nvidia_modules
    _unload_modules(available_modules, ["nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nvidia"])
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 257, in _unload_modules
    raise KernelSetupError("Cannot unload modules %s : %s" % (str(modules_to_unload), str(e)))
optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
modprobe: FATAL: Module nvidia is in use.

[951] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[951] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20210104T174910', 'requested_mode': 'integrated'}
```

This log makes no sense as there are no processes holding the GPU and I have manually and successfully ran:
`> sudo `

To be honest, I'd like to know how to help with this because this tool is incredibly helpful to me and I thank the developer for all the work!

**Comment by andrfgs** [comment]
Hey! I managed to "switch" the GPU by changing the startup mode and restarting the computer. So basically, the first time I boot my laptop, Optimus picks the correct option. It's just the switch that doesn't work.

**Comment by Kr1ss-XD** [comment]
Never mind my post above. The log shows that `optimus-manager` _was_ build against Python 3.9; my bad.

**Comment by andrfgs** [comment]
Yay asks whether or not you want to rebuild the packages in the terminal. Anyways, I'm guessing my issue is not with python itself but another thing.

**Comment by Kr1ss-XD** [comment]
Yeah guess that's correct. Sorry, no clue then.

**Comment by andrfgs** [comment]
Just so you know, I have ran:
`> sudo optimus-manager --switch integrated`

And the error log is now this :
```
[18] INFO: # Xorg pre-start hook
[18] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'hybrid', 'current_mode': None}
[18] INFO: Requested mode is: hybrid
[881] INFO: Available modules: ['nouveau', 'bbswitch', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[882] INFO: Unloading modules ['nouveau'] (if loaded)
[888] INFO: switching=none, nothing to do
[2234] INFO: Loading module nvidia
[2237] INFO: Loading module nvidia_drm
[3665] INFO: Loaded extra integrated-gpu Xorg options (0 lines)
[3665] INFO: Loaded extra nvidia-gpu Xorg options (0 lines)
[3665] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[3666] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20210104T180654', 'requested_mode': 'hybrid'}
[3666] INFO: Xorg pre-start hook completed successfully
```

This makes no sense since my request was to switch to `intel` or `integrated` not the `hybrid`, which is the current state I am on.

**Comment by Kr1ss-XD** [comment]
Hmm no it doesn't make sense. 

Did you try what happens if you omit `sudo` ?

**Comment by andrfgs** [comment]
Then it emits this log:
```
[20] INFO: # Xorg pre-start hook
[20] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'hybrid', 'current_mode': None}
[20] INFO: Requested mode is: hybrid
[920] INFO: Available modules: ['nouveau', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[920] INFO: Unloading modules ['nouveau'] (if loaded)
[923] INFO: switching=none, nothing to do
[958] INFO: Loading module nvidia
[1727] INFO: Loading module nvidia_drm
[2615] INFO: Loaded extra integrated-gpu Xorg options (0 lines)
[2616] INFO: Loaded extra nvidia-gpu Xorg options (0 lines)
[2616] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[2616] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20210104T181432', 'requested_mode': 'hybrid'}
[2617] INFO: Xorg pre-start hook completed successfully
```

Which, by the looks of it, fails to get the current mode. I also have no idea why the noveau module is loaded when I have
`switching=none` on my config file.

**Comment by Kr1ss-XD** [comment]
Yeah, `'current_mode': None` seems weird; sorry no idea. Guess we'll have to wait for @Askannz to have a look at your output.

Anyways, once your issue is solved, you don't need to run `optimus-manager` using `sudo`. Just run it as a normal user. :wink:

**Comment by Askannz** [comment]
Weird. Does it boot to the GPU mode you specify in your config file though ?

(Also please make new issue for this since it's not related to the Python version after all)

**Comment by kevindirect** [comment]
This seems to affect all AUR packages that depend on the AUR. I wrote a little script to update all of these pacakges (not just optimus-manager). This way you don't have to rebuild a bunch of AUR packages that don't need to be rebuilt:
```
#!/bin/bash
# Find the AUR packages that require python and rebuild them

aur=$(pacman -Qqm | sort);
req=$(pactree -rl -d 1 "python" | sort);
yay -S --rebuild $(comm -12 <(echo "$aur") <(echo "$req"));
```
I might write a hook to do this automatically, I'll comment here again if that works out

**Comment by Askannz** [comment]
I've bumped up the pkgrel in AUR for force AUR helpers to rebuild the package.

**Comment by kevindirect** [comment]
I tried writing the hook, but packages can't be build during a pacman hook (if someone knows a workaround let me know).
I wrote a warning hook you can add to warn you after python is updated, it's in this issue #453.

The pkgrel thing is nice but if it happens after python is updated a lot of people's systems will still break. It isn't ideal. It also affects all python AUR pacakges so I think it should be fixed elsewhere. If someone is more experienced in hooks, please contact me or modify the hook I wrote if there is a way to do it.

**Comment by kevindirect** [comment]
A hacky way I can think of is to somehow schedule the AUR python package rebuilds in the hook to occur after the current yay/pacman/whatever command ends. I don't know of a way to do this of the top of my head though.

**Comment by eonun** [comment]
The reason for this error is that the local python version does not match the version of python used by [optimus-manager](https://aur.archlinux.org/packages/optimus-manager/) in the AUR build package

You can install the version of [optimus-manager-git](https://aur.archlinux.org/packages/optimus-manager-git/) from the AUR repository and install it with the local python build.

It is recommended that the AUR release of the build package [optimus-manager](https://aur.archlinux.org/packages/optimus-manager/) add a dependency detection feature


出现这个错误的原因，应该是本地 python 的版本与 AUR 构建包中的 [optimus-manager](https://aur.archlinux.org/packages/optimus-manager/) 使用的 python 版本不一致导致的

可以安装 AUR 仓库中的 [optimus-manager-git](https://aur.archlinux.org/packages/optimus-manager-git/) 版本，通过本地  python 构建安装包来解决

建议 AUR 发布的构建包 [optimus-manager](https://aur.archlinux.org/packages/optimus-manager/) 添加依赖检测功能
