### ISSUE TITLE
Xorg pre-start setup error KeyError: 'intel' on an Intel system

### ISSUE THREAD

**Issue by gilabrantes** [Askannz/optimus-manager#358]
**Problem**
Have been using optimus-manager for the past few months without any issue, but recently did a system update which made my system to hang on boot, just before sddm would show.
Switching into a different tty I could still login to the system and found an error similar to the one below in the journal.
Changing the default mode from intel to nvidia gave me my sddm/kde back on boot but optimus-manager still throws the same error any time I try using it. Also I can't use intel mode at all. 

**System info**
- Arch
- KDE
- SDDM
- HP ZBook 15 G6 (Cannon Lake + Quadro RTX 3000 Mobile / Max-Q)
- Optimus Manager (Client) version 1.3 (from AUR)

**/etc/optimus-manager/optimus-manager.conf**
```
[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=nvidia
startup_auto_extpower_mode=nvidia
startup_mode=nvidia
switching=none
```

**Logs**
Running `optimus-manager --status` or any meaningful `optimus-manager` command results in the following error:
```
cat /var/log/optimus-manager/switch/switch-20201225T151916.log
[9] INFO: # Xorg pre-start hook
[9] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': None}
[9] INFO: Requested mode is: nvidia
[9] INFO: Checking for GDM display servers
[746] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[746] INFO: Unloading modules ['nouveau'] (if loaded)
[768] INFO: Loading module nvidia
[1399] INFO: Loading module nvidia_drm
[3108] INFO: Loaded extra Intel Xorg options (0 lines)
[3109] INFO: Loaded extra Intel Xorg options (0 lines)
[3109] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 46, in main
    configure_xorg(config, requested_mode)
  File "/usr/lib/python3.9/site-packages/optimus_manager/xorg.py", line 21, in configure_xorg
    xorg_conf_text = _generate_nvidia(config, bus_ids, xorg_extra)
  File "/usr/lib/python3.9/site-packages/optimus_manager/xorg.py", line 136, in _generate_nvidia
    text += "\tBusID \"%s\"\n" % bus_ids["intel"]
KeyError: 'intel'
[3109] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[3109] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20201225T151916', 'requested_mode': 'nvidia'}
```

**Comment by j4k0xb** [comment]
I had the same error
Fix was switching the bios setting from _discrete_ to _switchable_ GPU

**Comment by gilabrantes** [comment]
Indeed that fixed it, thank you!

**Comment by Askannz** [comment]
Added a check to make this error more explicit
https://github.com/Askannz/optimus-manager/commit/2fcd9356ccc93e2471187c66d0ca0bf43540a6ec
