### ISSUE TITLE
Switching to hybrid mode not working on master

### ISSUE THREAD

**Issue by Ligh7bringer** [Askannz/optimus-manager#371]
I think 8167cd82cfd80910e17a3729f959a044669bd741 broke switching to hybrid mode on AMD. I was able to fix the issue with the following change locally:

```patch
diff --git a/optimus_manager/xorg.py b/optimus_manager/xorg.py
index 11f573e..5460124 100644
--- a/optimus_manager/xorg.py
+++ b/optimus_manager/xorg.py
@@ -208,7 +208,10 @@ def _generate_hybrid(config, bus_ids, xorg_extra):
            "\tOption \"AllowNVIDIAGPUScreens\"\n" \
            "EndSection\n\n"
 
-    text += _make_intel_device_section(config, bus_ids, xorg_extra_lines_integrated)
+    if "intel" in bus_ids:
+        text += _make_intel_device_section(config, bus_ids, xorg_extra_lines_integrated)
+    else:
+        text += _make_amd_device_section(config, bus_ids, xorg_extra_lines_integrated)
 
     text += "Section \"Screen\"\n" \
            "\tIdentifier \"integrated\"\n" \
```

An example log of a failed switch:

```
[18] INFO: # Xorg pre-start hook
[18] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'hybrid', 'current_mode': None}
[18] INFO: Requested mode is: hybrid
[261] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[261] INFO: Unloading modules ['nouveau'] (if loaded)
[270] INFO: switching=none, nothing to do
[337] INFO: Loading module nvidia
[747] INFO: Loading module nvidia_drm
[2661] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 52, in main
    configure_xorg(config, requested_mode)
  File "/usr/lib/python3.9/site-packages/optimus_manager/xorg.py", line 26, in configure_xorg
    xorg_conf_text = _generate_hybrid(config, bus_ids, xorg_extra)
  File "/usr/lib/python3.9/site-packages/optimus_manager/xorg.py", line 211, in _generate_hybrid
    text += _make_intel_device_section(config, bus_ids, xorg_extra_lines_integrated)
  File "/usr/lib/python3.9/site-packages/optimus_manager/xorg.py", line 282, in _make_intel_device_section
    text += "\tBusID \"%s\"\n" % bus_ids["intel"]
KeyError: 'intel'
[2662] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[2662] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20210206T155314', 'requested_mode': 'hybrid'}
```

**Comment by Kr1ss-XD** [comment]
Nice! Thx for sharing the patch.

**Comment by Askannz** [comment]
Ah yep, thanks for catching that.
