### ISSUE TITLE
Rebooting when in NVIDIA mode breaks PCI rescanning

### ISSUE THREAD

**Issue by Adamskye** [Askannz/optimus-manager#390]
**Bug description**
I'm using optimus-manager with switching method set to none, PCI power control enabled, PCI remove enabled and PCI reset set to function level. My startup mode is set to integrated. This setup works normally but breaks when I reboot whilst in NVIDIA mode.

After rebooting while in NVIDIA mode, when I try to switch to my NVIDIA card, optimus-manager fails to re-enable my NVIDIA GPU as it fails to show in PCI bus.

The work-around I'm using is to use a script which waits 3 seconds when rescanning to allow the NVIDIA GPU enough time to show up in the PCI bus. This switching method is a few seconds slower, which implies that optimus-manager isn't waiting long enough for rescanning to work. Additionally, optimus-manager gives up rescanning after only one attempt.

**Logs**
```
[6] INFO: # Xorg pre-start hook
[6] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': 'integrated'}
[6] INFO: Requested mode is: nvidia
[188] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[188] INFO: Unloading modules ['nouveau'] (if loaded)
[190] INFO: switching=none, nothing to do
[296] INFO: Nvidia card not visible in PCI bus, rescanning
[296] INFO: Rescanning PCI bus
[309] ERROR: Nvidia card not showing up in PCI bus after rescan. Continuing anyways.
[309] INFO: Resetting Nvidia PCI device
[309] INFO: Performing function-level reset of Nvidia
[321] ERROR: Nvidia PCI reset failed. Continuing anyways. Error is: Failed to perform PCI reset: Nvidia not in PCI bus
[321] INFO: Setting Nvidia PCI power state to on
[333] ERROR: Cannot set PCI power management state. Continuing anyways. Error is: Nvidia not in PCI bus
[349] INFO: Loading module nvidia
[556] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 245, in _load_module
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'modprobe nvidia NVreg_UsePageAttributeTable=1' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 51, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 22, in setup_kernel_state
    _nvidia_up(config, hybrid=(requested_mode == "hybrid"))
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 95, in _nvidia_up
    _load_nvidia_modules(config, available_modules)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 164, in _load_nvidia_modules
    _load_module(available_modules, "nvidia", options=nvidia_options)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 249, in _load_module
    raise KernelSetupError(f"Error running modprobe for {module}: {e.stderr}") from e
optimus_manager.kernel.KernelSetupError: Error running modprobe for nvidia: None
[556] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[556] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20210307T132138', 'requested_mode': 'nvidia'}
```

**Some specs**
- Linux 5.11.1-1-MANJARO
- I'm not using a desktop manager, but I am using i3wm.
- Display manager is LightDM.
- Lenovo Legion 5 15IMH05H with an Intel UHD 630 and NVIDIA RTX 2060 Mobile.
- I'm using optimus-manager 1.4-2.
- This issue doesn't occur with a custom script.

**Comment by seymromero** [comment]
Same Issue here

**Comment by seymromero** [comment]
oh manjaro, try using the stable kernel version tho

**Comment by seymromero** [comment]
Oh my god, That's right, I forgot the drivers, thank you for making me comment here

**Comment by nwildner** [comment]
Hello @Adamskye . Are you still facing this issue with more modern Kernel and Nvidia drivers versions and using `optimus-manager-git`?

Since the last update on this case was from 2+ years ago, we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.

**Comment by Adamskye** [comment]
> Hello @Adamskye . Are you still facing this issue with more modern Kernel and Nvidia drivers versions and using `optimus-manager-git`?
> 
> Since the last update on this case was from 2+ years ago, we'll keep this case opened for some days and close it if no answer is provided.
> 
> Have a nice week ahead.

Unfortunately, I no longer have the laptop I had this issue with nor does my current PC have an Nvidia GPU, so I can't confirm if this issue still occurs. From what I can recall, I was able to make the issue go away though I don't remember how (I probably just switched to using hybrid mode instead of Nvidia mode). I left this issue open since I wasn't exactly sure what was causing this nor if it was fixed.

**Comment by nwildner** [comment]
Ok. Thanks for confirming. We'll close this case then for backlog purposes.
Thanks for the input.
