### ISSUE TITLE
Config validate: 

### ISSUE THREAD

**Issue by blackPantherOS** [Askannz/optimus-manager#391]
**Describe the bug**

When 'dynamic_power_management=no" and also
 the 'dynamic_power_management_memory_threshold=' value is empty, 0 or -1 in configs, cannot start daemon and we get this error: _"non-blank integer value required"_

```
[12] ERROR: Daemon startup error
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/optimus_manager/hooks/pre_daemon_start.py", line 27, in main
    config = load_config()
  File "/usr/lib/python3.7/site-packages/optimus_manager/config.py", line 16, in load_config
    config = _load_config()
  File "/usr/lib/python3.7/site-packages/optimus_manager/config.py", line 28, in _load_config
    _validate_config(base_config)
  File "/usr/lib/python3.7/site-packages/optimus_manager/config.py", line 132, in _validate_config
    raise ConfigError(error_msg)
optimus_manager.config.ConfigError: Config parsing : error in option "dynamic_power_management_memory_threshold" in section [nvidia] : non-blank integer value required
[12] INFO: Writing state {'type': 'startup_failed', 'startup_mode': None, 'daemon_run_id': '20210310T121854'}
```

**Comment by Askannz** [comment]
Thanks, fixed.

**Comment by kamalkech** [comment]
@Askannz how fixed ? because i get the same error
