### ISSUE TITLE
issue after LATEST update 

### ISSUE THREAD

**Issue by cyrstem** [Askannz/optimus-manager#444]
**Describe the bug**

**System info**
Please include :
- Manjaro
- GNOME
- GDM
- RAZER BLADE 2018
- The version of optimus-manager you are using : latest stable 

**Logs**
[16] INFO: # Xorg pre-start hook
[34] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': 'integrated'}
[34] INFO: Requested mode is: nvidia
[582] INFO: Available modules: ['nouveau', 'bbswitch', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[582] INFO: Unloading modules ['nouveau'] (if loaded)
[585] INFO: Loading module bbswitch
[587] INFO: Setting GPU power to ON via bbswitch
[1986] INFO: Loading module nvidia
[3610] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 245, in _load_module
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'modprobe nvidia NVreg_UsePageAttributeTable=1' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 51, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 22, in setup_kernel_state
    _nvidia_up(config, hybrid=(requested_mode == "hybrid"))
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 95, in _nvidia_up
    _load_nvidia_modules(config, available_modules)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 164, in _load_nvidia_modules
    _load_module(available_modules, "nvidia", options=nvidia_options)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 249, in _load_module
    raise KernelSetupError(f"Error running modprobe for {module}: {e.stderr}") from e
optimus_manager.kernel.KernelSetupError: Error running modprobe for nvidia: None
[3613] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[3613] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20211014T220523', 'requested_mode': 'nvidia'}

**Comment by LukeFernandes** [comment]
To second this. I have the same issue following the latest update to the nvidia driver, bbswitch and Manjaro kernel. I'm using Cinnamon on a ThinkPad P72.
My error is the same or very similar. 
It is also accompanied by a (non-Optimus-Manager) error at the blank screen phase of the switch (see attached and below):
NVRM: This is a 64-bit BAR mapped above 4GB by the system
NVRM: BIOS or the Linux kernel, but the PCI bridge
NVRM: immediately upstream of this GPU does not define
NVRM: a matching prefetchable memory window.

This isn't an Optimus Manager bug as it's a failure of the nvidia module to start. Nevertheless this is a good place to discuss it. Any help very welcome!

**Comment by rogpld** [comment]
Adding `pcie_port_pm=off` to the kernel parameters also fixed it for me. 

I'm on `Linux Workspace 5.10.70-1-MANJARO`.

**Comment by cyrstem** [comment]
@mauricioquintela  where do i add this lines?

**Comment by mauricioquintela** [comment]
@cyrstem it is a kernel parameter, so to `/etc/default/grub`. dont forget to `sudo update-grub` afterwards

**Comment by rogpld** [comment]
@cyrstem or follow [this](https://wiki.archlinux.org/title/kernel_parameters) if you have a different bootloader.

**Comment by nwildner** [comment]
@cyrstem , are you still interested on this issue? Have you had the time to update your bootloader settings?

Since the last comment on this case was from 2,5 years ago and a lot has changed in many aspects of multiple software(nvidia, optimus-manager, linux), we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.
