### ISSUE TITLE
PackageNotFoundError

### ISSUE THREAD

**Issue by codysork** [Askannz/optimus-manager#455]
Whenever I run optimus-manager, it throws a PackageNotFoundError with a traceback.

**System info**

- Distro: Arch Linux
- DE: none
- WM: i3
- DM: SDDM
- optimus-manager version : 1.4

**Error**

Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 33, in <module>
    sys.exit(load_entry_point('optimus-manager==1.4', 'console_scripts', 'optimus-manager')())
  File "/usr/bin/optimus-manager", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for optimus-manager

**Logs**

No recent logs could be found in `/var/log/optimus-manager/switch/` or `/var/log/optimus-manager/daemon/` when this error happened.

**Comment by Askannz** [comment]
It's caused by Arch upgrading from Python 3.9 to 3.10. You can fix it by rebuilding the package from AUR. Or if you use an AUR helper like yay, just upgrade to the latest version, I've pushed an update to force AUR helpers to rebuild.

**Comment by BrandonMoo** [comment]
Hi, I have just upgrade the optimus-manager to 1.4-3 like this:
`yay -S optimus-manager`
but there is still errors of:
`~ >>> optimus-manager --status                                                                                            
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 33, in <module>
    sys.exit(load_entry_point('optimus-manager==1.4', 'console_scripts', 'optimus-manager')())
  File "/usr/bin/optimus-manager", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: optimus-manager
`
