### ISSUE TITLE
Cannot open Optimus-Manager

### ISSUE THREAD

**Issue by RedDragonTix** [Askannz/optimus-manager#466]
```
ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20220117T204630.log
Cannot execute command because of previous errors.
```

log file:
```
[10] INFO: # Xorg pre-start hook
[11] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[11] INFO: Requested mode is: integrated
[124] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[124] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[127] INFO: Cannot unload modules: None
[127] INFO: Waiting 1s and retrying.
[1269] INFO: Cannot unload modules: None
[1269] INFO: Waiting 1s and retrying.
[2279] INFO: Cannot unload modules: None
[2279] INFO: Waiting 1s and retrying.
[3289] INFO: Cannot unload modules: None
[3290] INFO: Waiting 1s and retrying.
[4300] INFO: Cannot unload modules: None
[4300] INFO: Waiting 1s and retrying.
[5310] INFO: Max tries (6) exceeded
[5310] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 269, in _unload_modules
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 51, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 25, in setup_kernel_state
    _nvidia_down(config)
  File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 104, in _nvidia_down
    _unload_nvidia_modules(available_modules)
  File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 214, in _unload_nvidia_modules
    _unload_modules(available_modules, ["nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nvidia"])
  File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 277, in _unload_modules
    raise KernelSetupError(f"Cannot unload modules {modules_to_unload}: {e.stderr}") from e
optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia']: None
[5311] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[5311] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20220117T204630', 'requested_mode': 'integrated'}
```
What am I did wrong?

**Comment by RedDragonTix** [comment]
OK I found out that issue, it works now, it's stupid gdm not compatible with optimus-manager and had to replace with gdm-prime

**Comment by kamalkech** [comment]
i install gdm-prime but still i get this error, i try to reboot pc but issue not fixed !:

```
ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20220205T220252.log
Cannot execute command because of previous errors.
```

**Comment by Askannz** [comment]
@kamalkech (if you're still around) this error message can be caused by anything, please open a new issue with more logs.

**Comment by linsyking** [comment]
> [@kamalkech](https://github.com/kamalkech) (if you're still around) this error message can be caused by anything, please open a new issue with more logs.

I had the issue, full log is:

```
[9] INFO: # Xorg pre-start hook
[9] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[9] INFO: Requested mode is: integrated
[48] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[48] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[52] INFO: Cannot unload modules: None
[52] INFO: Waiting 1s and retrying.
[1061] INFO: Cannot unload modules: None
[1061] INFO: Waiting 1s and retrying.
[2070] INFO: Cannot unload modules: None
[2071] INFO: Waiting 1s and retrying.
[3080] INFO: Cannot unload modules: None
[3080] INFO: Waiting 1s and retrying.
[4087] INFO: Cannot unload modules: None
[4087] INFO: Waiting 1s and retrying.
[5094] INFO: Max tries (6) exceeded
[5094] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/optimus_manager/kernel.py", line 269, in _unload_modules
    subprocess.check_call(
    ~~~~~~~~~~~~~~~~~~~~~^
        f"modprobe -r {' '.join(modules_to_unload)}",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        shell=True, text=True, stderr=subprocess.PIPE, stdout=subprocess.DEVNULL)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 419, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 51, in main
    setup_kernel_state(config, prev_state, requested_mode)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/optimus_manager/kernel.py", line 25, in setup_kernel_state
    _nvidia_down(config)
    ~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/site-packages/optimus_manager/kernel.py", line 104, in _nvidia_down
    _unload_nvidia_modules(available_modules)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/optimus_manager/kernel.py", line 214, in _unload_nvidia_modules
    _unload_modules(available_modules, ["nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nvidia"])
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/optimus_manager/kernel.py", line 277, in _unload_modules
    raise KernelSetupError(f"Cannot unload modules {modules_to_unload}: {e.stderr}") from e
optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia']: None
[5099] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[5099] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20250206T195638', 'requested_mode': 'integrated'}
```


I suspect this is an x server issue.

**Comment by es20490446e** [comment]
What is your:
- distro
- kernel
- driver
