### ISSUE TITLE
Unable to switch from integrated mode

### ISSUE THREAD

**Issue by yashlakhtariya** [Askannz/optimus-manager#528]
When switched to integrated mode, unable to switch back to any mode because optimus manager service fails. The only way is to edit file and switch modes at startup 

optimus-manager --status

```
ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20221201T144727.log
Cannot execute command because of previous errors.

```

Garuda Linux
GDM
Pavilion-15-ec2075ax
AMD Ryzen 5 5600H with Radeon Graphics
Geforce RTX 3050 Laptop GPU 

File: /etc/optimus-manager/optimus-manager.conf
```
[amd]
DRI=3
driver=modesetting
tearfree=yes

[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
dynamic_power_management=coarse
ignore_abi=yes
modeset=yes
options=overclocking, triple_buffer

[optimus]
auto_logout=yes
pci_power_control=yes
pci_remove=no
pci_reset=no
startup_auto_battery_mode=integrated
startup_auto_extpower_mode=nvidia
startup_mode=auto
switching=bbswitch
```
Log 

File: /var/log/optimus-manager/switch/switch-20221201T144727.log

```
[9] INFO: # Xorg pre-start hook
[21] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': 'hybrid'}
[21] INFO: Requested mode is: integrated
[127] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[127] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[190] INFO: Cannot unload modules: None
[190] INFO: Waiting 1s and retrying.
[1196] INFO: Cannot unload modules: None
[1196] INFO: Waiting 1s and retrying.
[2202] INFO: Cannot unload modules: None
[2202] INFO: Waiting 1s and retrying.
[3207] INFO: Cannot unload modules: None
[3207] INFO: Waiting 1s and retrying.
[4212] INFO: Cannot unload modules: None
[4212] INFO: Waiting 1s and retrying.
[5218] INFO: Max tries (6) exceeded
[5218] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 269, in _unload_modules
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 51, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 25, in setup_kernel_state
    _nvidia_down(config)
  File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 104, in _nvidia_down
    _unload_nvidia_modules(available_modules)
  File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 214, in _unload_nvidia_modules
    _unload_modules(available_modules, ["nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nvidia"])
  File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 277, in _unload_modules
    raise KernelSetupError(f"Cannot unload modules {modules_to_unload}: {e.stderr}") from e
optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia']: None
[5218] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[5218] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20221201T144727', 'requested_mode': 'integrated'}
```

**Comment by Taero6** [comment]
i have the same problem :(
and exactly the same system (garuda) and laptop with the same cpu and gpu.

**Comment by Taero6** [comment]
ok i now know that changing the kernel was the solution ("linux-zen" > "linux"   ...these are the names of the kernels in the grub menu)
maybe a kernel-update caused the problem

**Comment by yashlakhtariya** [comment]
Hey @Taero6! Thanks for your help, but the issue remains the same even with linux kernel. Changing kernel doesn't solve the issue.

**Comment by guillaumemichel** [comment]
Same problem here :(

**Comment by yaourtiere** [comment]
I got the same issue lately with ``linux-hardened``, I resolved it by switching to the ``linux`` kernel. Could be interesting to dig into this issue.

**Comment by nwildner** [comment]
Hello @yashlakhtariya , are you still facing this issue on a more modern installation of Linux(kernel + nvidia drivers + optimus-manager) ?

Also, please track the `optimus-manager-git` package since this received a lot of updates from the time this was originally reported by you.

Cheers.

**Comment by caffeine-addictt** [comment]
@nwildner i got the same issue right now, on a fresh install of Qtile (Xorg) on archlinux using SDDM. Log file is identical to the originally filed issue.

I'm not too familiar with GPU drivers on linux and not sure if its the same cause, but it is a bit of a doozy because `root` is using the nvidia card (see attached) to run sddm but userspace cant? When i kill the process running nvidia in root it kills the whole session and trying from tty doesn't seem to be of much help either.

`sudo fuser -v /dev/nvidia*`
![image](https://github.com/user-attachments/assets/0a84f0c1-a2d0-4337-bff2-84c5bef0dc53)

Realize it might make more sense to create a separate issue, but since this looks related, thought it'd post this here first. LMK if you'd like me to open an issue instead.

Appreciate all the help but honestly, I'm at a loss haha.
