### ISSUE TITLE
Cannot start optimus-manager-qt

### ISSUE THREAD

**Issue by greenhandzdl** [Askannz/optimus-manager#546]
**Describe the bug**
```
➜  ~ optimus-manager-qt                                            
Unable to read current mode from Optimus Manager state file
[1]    150907 IOT instruction (core dumped)  optimus-manager-qt
```

**System info**
Please include :
- Your distribution :Arch Linux
- Your desktop manager (KDE, GNOME, Cinnamon...), if you have one :Gnome
- You display manager (SDDM, GDM, LightDM...), if you have one. If you do not know, you are probably using the one coming with your desktop manager. :GDM
- Your laptop model, if you think it could be related to the problem
- The version of optimus-manager you are using : latest stable release (optimus-manager), or the latest Git version (optimus-manager-git) : latest stable release 
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`, if you made one
```
➜  ~ cat /etc/optimus-manager/optimus-manager.conf
cat: /etc/optimus-manager/optimus-manager.conf: No such file or directory
```
**Logs**
Run `optimus-manager --status` in a console, and if an error message appears, post it here. The message should also point you to a log path, attach it here as well. If there is no error message but you are still experiencing issues, grab the most recent files in `/var/log/optimus-manager/switch/` and `/var/log/optimus-manager/daemon/`.
```
➜  ~ optimus-manager --status
ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20230730T204825.log
Cannot execute command because of previous errors.
➜  ~ cat /var/log/optimus-manager/switch/switch-20230730T204825.log

[7] INFO: # Xorg pre-start hook
[7] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[7] INFO: Requested mode is: integrated
[25] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[25] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[27] INFO: switching=none, nothing to do
[41] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 52, in main
    configure_xorg(config, requested_mode)
  File "/usr/lib/python3.11/site-packages/optimus_manager/xorg.py", line 18, in configure_xorg
    bus_ids = get_gpus_bus_ids()
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/optimus_manager/pci.py", line 100, in get_gpus_bus_ids
    raise PCIError("Cannot find the integrated GPU. Is this an Optimus system ?")
optimus_manager.pci.PCIError: Cannot find the integrated GPU. Is this an Optimus system ?
[42] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[42] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20230730T204825', 'requested_mode': 'integrated'}

```

**Comment by awsms** [comment]
I'm getting this exact issue since a BIOS update. Mind reopening it?
