### ISSUE TITLE
Optimus-manager service failed boot-time startup

### ISSUE THREAD

**Issue by JonasFranke** [Askannz/optimus-manager#579]
**Describe the bug**
When starting optimus-manager I get this error:
```
ERROR: the optimus-manager service failed boot-time startup.
Log at /var/log/optimus-manager/daemon/daemon-20240922T121107.log
Error loading config file : Cannot find header for section [optimus]
```

**System info**
Please include :
- Your distribution: Arch (btw)
- Your desktop manager GNOME
- You display manager GDM
- The version of optimus-manager you are using : latest

**Logs**
```
[43] INFO: # Daemon pre-start hook
[43] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[44] INFO: Copying /etc/optimus-manager/optimus-manager.conf to /var/lib/optimus-manager/tmp/config_copy.conf
[45] ERROR: Daemon startup error
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/optimus_manager/hooks/pre_daemon_start.py", line 27, in main
    config = load_config()
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/optimus_manager/config.py", line 16, in load_config
    config = _load_config()
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/optimus_manager/config.py", line 28, in _load_config
    _validate_config(base_config)
  File "/usr/lib/python3.12/site-packages/optimus_manager/config.py", line 114, in _validate_config
    raise ConfigError("Cannot find header for section [%s]" % section)
optimus_manager.config.ConfigError: Cannot find header for section [optimus]
[48] INFO: Writing state {'type': 'startup_failed', 'startup_mode': None, 'daemon_run_id': '20240922T121107'}
[0] INFO: # Commands daemon
[0] INFO: Opening UNIX socket
[1] INFO: Awaiting commands
```

**Comment by es20490446e** [comment]
See https://github.com/Askannz/optimus-manager/issues/578.
