### ISSUE TITLE
I confirm the issue still persists even after your update

### ISSUE THREAD

**Issue by Hikmat-E-Ustad** [Askannz/optimus-manager#580]
I confirm the issue still persists even after your update

```
hikmateustad@hikmateustad-dell ~ % optimus-manager --status
ERROR: the optimus-manager service failed boot-time startup.
Log at /var/log/optimus-manager/daemon/daemon-20240922T160744.log
Error loading config file : Cannot find header for section [optimus]
1 hikmateustad@hikmateustad-dell ~ % nano /var/log/optimus-manager/daemon/daemon-20240922T160744.log
hikmateustad@hikmateustad-dell ~ % 

```

```
  GNU nano 8.2                                   /var/log/optimus-manager/daemon/daemon-20240922T160744.log                                             
[525] INFO: # Daemon pre-start hook
[525] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[544] INFO: Copying /etc/optimus-manager/optimus-manager.conf to /var/lib/optimus-manager/tmp/config_copy.conf
[570] ERROR: Daemon startup error
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/optimus_manager/hooks/pre_daemon_start.py", line 27, in main
    config = load_config()
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/optimus_manager/config.py", line 16, in load_config
    config = _load_config()
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/optimus_manager/config.py", line 28, in _load_config
    _validate_config(base_config)
  File "/usr/lib/python3.12/site-packages/optimus_manager/config.py", line 114, in _validate_config
    raise ConfigError("Cannot find header for section [%s]" % section)
optimus_manager.config.ConfigError: Cannot find header for section [optimus]
[576] INFO: Writing state {'type': 'startup_failed', 'startup_mode': None, 'daemon_run_id': '20240922T160744'}
[2] INFO: # Commands daemon
[2] INFO: Opening UNIX socket
[2] INFO: Awaiting commands


```

_Originally posted by @Hikmat-E-Ustad in https://github.com/Askannz/optimus-manager/issues/578#issuecomment-2366718233_

**Comment by es20490446e** [comment]
Lets handle this at https://github.com/Askannz/optimus-manager/issues/580.
