### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'optimus-manager==1.0' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by devsnek** [Askannz/optimus-manager#91]
**Describe the bug**
Trying to run optimimus-manager crashes with `pkg_resources.DistributionNotFound: The 'optimus-manager==1.0' distribution was not found and is required by the application`

**System info**
Please include :
- Your distribution: Manjaro
- Your desktop manager: GDM
- You display manager: GDM
- Your laptop model: Thinkpad X1 Extreme

**Logs**
```
$ optimus-manager
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'optimus-manager==1.0' distribution was not found and is required by the application
```

**Comment by Askannz** [comment]
You're trying to run the program through Python 2, which won't work. How did you install the package ?

**Comment by devsnek** [comment]
I installed it with `yay -S optimus-manager`

**Comment by devsnek** [comment]
replacing `/usr/bin/python` with `/usr/bin/python3` in the service file and whatnot fixed this. perhaps that should be the default? regardless of whether someone has `python` set to 2 or 3, `python2` and/or `python3` should always exist.

**Comment by Askannz** [comment]
I thought Python 2 was always the default on Arch-based distros, `guess I was wrong.

Thanks for reporting, will fix that.

**Comment by Askannz** [comment]
Should be fixed in the latest master, closing this issue. Feel free to reopen if it isn't.

**Comment by Araly** [comment]
Reopening this issue, last update broke optimus-manager, looks like the same issue as here.

**Describe the bug**
Cannot switch to another mode.

```
$ optimus-manager --switch nvidia
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'optimus-manager==1.2.2' distribution was not found and is required by the application
```

I get this error with any arguments (or lack of} when calling `optimus-manager`, even when trying to get a help

```$ sudo systemctl status optimus-manager.service
● optimus-manager.service - Optimus Manager Commands Daemon
   Loaded: loaded (/usr/lib/systemd/system/optimus-manager.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-11-15 16:19:38 CET; 7min ago
  Process: 3138 ExecStartPre=/usr/bin/prime-switch-boot (code=exited, status=0/SUCCESS)
  Process: 3142 ExecStart=/usr/bin/python3 -u /usr/bin/optimus-manager-daemon (code=exited, status=1/FAILURE)
 Main PID: 3142 (code=exited, status=1/FAILURE)

nov. 15 16:19:38 valhalla python3[3142]:     working_set = WorkingSet._build_master()
nov. 15 16:19:38 valhalla python3[3142]:   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 58>
nov. 15 16:19:38 valhalla python3[3142]:     ws.require(__requires__)
nov. 15 16:19:38 valhalla python3[3142]:   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 90>
nov. 15 16:19:38 valhalla python3[3142]:     needed = self.resolve(parse_requirements(requirements))
nov. 15 16:19:38 valhalla python3[3142]:   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 78>
nov. 15 16:19:38 valhalla python3[3142]:     raise DistributionNotFound(req, requirers)
nov. 15 16:19:38 valhalla python3[3142]: pkg_resources.DistributionNotFound: The 'optimus-manager==1.2.2' distributio>
nov. 15 16:19:38 valhalla systemd[1]: optimus-manager.service: Main process exited, code=exited, status=1/FAILURE
nov. 15 16:19:38 valhalla systemd[1]: optimus-manager.service: Failed with result 'exit-code'.
```

**System info**
I'm using:
- Manjaro
- i3wm
- LightDM
- version 1.2.2-2 from the manjaro repositories, not from the AUR

**Logs**
https://pastebin.com/0hNZFHsK

**Comment by Araly** [comment]
Apparently #174 seems to be the right issue. I uninstalled optimus-manager and reinstalled it, from the AUR this time, and now it works again

**Comment by Askannz** [comment]
Yes, optimus-manager was broken by the Python 3.8 update on Arch, this isn't related to the current issue.
